### ISSUE TITLE
undefined reference to `sleepdelay(int)'

### ISSUE THREAD

**Issue by manuchSP** [agnunez/moco2#1]
No consigo compilar con la wifi inabilitada, me sale el error : "undefined reference to `sleepdelay(int)'"

... alguna idea de que estoy haciendo mal?

**Comment by agnunez** [comment]
Comprueba que tienes todos ficheros en el directorio al compilar, en concreto el wifimanager.cpp pues en este fichero es donde está definida esa función void sleepdelay(int);
